#!/bin/bash

unique_ips() {
    tshark -r $1 -T fields -e ip.src | sort | uniq > unique_ips.txt
    tshark -r $1 -T fields -e ip.dst | sort | uniq >> unique_ips.txt
    cat unique_ips.txt | sort | uniq | tee unique_ips.txt
    rm unique_ips.txt
}

http_requests() {
    tshark -r $1 -Y http.request -T fields -e http.request.full_uri
}

stat() {
    echo -n "GET REQUESTES: "
    tshark -r $1 -Y "http.request.method == 'GET'" | sort | uniq | wc -l
    echo -n "POST REQUESTES: "
    tshark -r $1 -Y "http.request.method == 'POST'" | sort | uniq | wc -l

    echo -n "PUSH/ACK REQUESTS: "
    tshark -r $1 -Y "tcp.flags == 0x018" | sort | uniq | wc -l
}


# find any weard 'user-agent' string generated by malware
user_agents() {
    tshark -r $1 -T fields -e http.user_agent
}

stat "$1"